---
- name: Run python scripts in remote machine
  hosts: localhost
  become: yes
  tasks:
    - name: "check for pyton installation"
      raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python
    - name: "install python if does not exists"
      raw: yum -y install python
      when: check_python.rc != 0
    - name: "Install git"
      yum:
        name: git
        state: present
        update_cache: yes
    - name: "creating directory"
      file:
        state: directory
        path: /home/ec2-user/ansible_swati/test_python
        owner: ec2-user
        group: ec2-user
        mode: 0750
    - name: "clone transformer repo"
      ansible.builtin.git:
        repo: https://github.com/SwatiJain0730/container-transform.git
        dest: /home/ec2-user/ansible_swati/test_python
#    - name: "copy json file"
#      synchronize:
#        mode: push
#        src: /home/ec2-user/app_repo/jobs.json
#        dest: /home/ec2-user/ansible_swati/test_python/container-transform/
#      delegate_to: "localhost"
    - name: "install container transform"
      shell :
          "cd /home/ec2-user/ansible_swati/test_python &&  pip3 install ."
#      register: result0
#    - debug: msg="{{result0.stdout}}"
    - name: "transform marathon json"
      command: "container-transform -i marathon -o helm /home/ec2-user/app_repo/jobs.json"
      register: out
#    - debug: msg="{{ out.stdout }}"
    - name: "Print the message"
      debug:
        msg: "{{ out.stdout }}"


